server:
  port: 8080

devtools:
  livereload:
    enabled: true # 정적파일들의 실시간 갱신


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: juyoung
    password: pass

    oauth2:
      client:
        registration:
          google:
            client-id: 434541373271-h977ssvpjlv003tdkfof6f49pqg8fsqr.apps.googleusercontent.com
            client-secret: d9k1lSwtPwrfHBtpwrp-fTac