server:
  port: 8080
#  servlet:
#    context-path: /auth

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: juyoung
    password: pass
    #    initialization-mode: always

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    #    root: INFO
    org.springframework.security: debug
#    org.hibernate.SQL: debug
#    org.h2: debug
    org.springframework.security.oauth2.jwt: debug

my-app:
  client-id: myApp
  client-secret: password
  user-id: user@gmail.com
  user-password: 123
  admin-id: admin@gmail.com
  admin-password: 123