# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

## 토큰 발급
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic myApp password

grant_type=password&username=admin@gmail.com&password=123

###

## 회원가입
POST http://localhost:8080/sign-up
Content-Type: application/json
Accept: application/json

< session-sign-up.json

### 로그인
POST http://localhost:8080/sign-in
Content-Type: application/json
Accept: application/json

{
  "email": "user@gmail.com",
  "password": "123"
}

###
GET http://localhost:8080/tokens

###
GET http://localhost:8080/oauth/check_token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTkwNzI4NzEsInVzZXJfbmFtZSI6InVzZXIiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiNjgwNGE1ZmYtNDI5NC00NzM4LWIxYTctNjk3OTBmMjZhMTIwIiwiY2xpZW50X2lkIjoibXlBcHAiLCJzY29wZSI6WyJzY29wZSJdfQ.4XZE_o2pevNIvYz-JsufUmnJqYF4gcXYeDWwZ6lg95M

###