server:
  port: 8083
  servlet:
    context-path: /ui

spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: fooClientIdPassword
            client-secret: secret
            scope: read,write,foo
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/ui/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            token-uri: http://localhost:8081/auth/oauth/token
            user-info-uri: http://localhost:8082/account/users/extra
            user-name-attribute: user_name
  thymeleaf:
    cache: false

logging:
  level:
    org.org.springframework: INFO