spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

datasource:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_seq: true
        format_sql: true