spring:
  datasource:
    url: jdbc:mysql://localhost:3306/colini
    username: friday
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    ROOT : DEBUG
#    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.springframework.security.oauth2.jwt: DEBUG